version: '3.2'

services:
  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411

  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672

  db-movie-service:
    image: mysql:8.0
    container_name: db-movie-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_movie
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/db_movie.sql
      - ./mysql-movie-volume:/var/lib/mysql
    ports:
      - 3307:3306

  db-series-service:
    image: mysql:8.0
    container_name: db-series-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_series
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/db_series.sql
      - ./mysql-series-volume:/var/lib/mysql
    ports:
      - 3308:3306

  db-catalog-service:
    image: mongo:4.4.2
    container_name: db-catalog-service
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db_catalog
      MONGO_INIT_ROOT_USERNAME: marcos
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - ./scripts:/docker-entrypoint-initb.d/db_catalog_init.js:ro
      - ./mongo-catalog-volume:/data/db
    ports:
      - 27019:27017

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    depends_on:
      - zipkin-service
    ports:
      - 8761:8761

  config-server:
    build: config-server
    container_name: config-server
    depends_on:
      - eureka-service
    ports:
      - 8888:8888

  movie-service:
    build: movie-service
    container_name: movie-service
    restart: always
    links:
      - db-movie-service:mysql:8.0
    depends_on:
      - config-server
      - db-movie-service
    ports:
      - 8001:8001

  catalog-service:
    build: catalog-service
    container_name: catalog-service
    restart: always
    depends_on:
      - config-server
      - movie-service
      - serie-service
      - db-catalog-service
    ports: 8002:8002

  serie-service:
    build: serie-service
    container_name: serie-service
    restart: always
    links:
      - db-series-service:mysql:8.0
    depends_on:
      - config-server
      - db-series-service
    ports: 8003:8003

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    depends_on:
      - catalog-service
    ports:
      - 8080:8080