version: '3.2'

services:
  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411

  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672

  db-movie-service:
    image: mysql:8.0
    container_name: db-movie-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_movie
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/db_movie.sql
      - ./mysql-movie-volume:/var/lib/mysql
    ports:
      - 3307:3306

  db-series-service:
    image: mysql:8.0
    container_name: db-series-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_series
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/db_series.sql
      - ./mysql-series-volume:/var/lib/mysql
    ports:
      - 3308:3306

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    depends_on:
      - zipkin-service
    ports:
      - 8761:8761

  config-server:
    build: config-server
    container_name: config-server
    depends_on:
      - eureka-service
    ports:
      - 8888:8888

#  api-gateway:
#    build: api-gateway
#    container_name: api-gateway
#    ports:
#      - 8080:8080